version: '3'

networks:
    nmpn:

services:
    # nginx
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        volumes:
            -   ./src:/var/www/project
            -  ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            -   php
            - mysql
        ports:
            - '8080:80'
        networks:
            - nmpn

    #myql
    mysql:
        image: mysql:8
        container_name: mysql
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
            - ./mysql:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 123
            MYSQL_USER: dbuser
            MYSQL_PASSWORD: 123
            MYSQL_DATABASE: mysqldb
        ports:
            -   ":4306:3306"
        networks:
            - nmpn

    #php
    php:
        build:
            context: ./
            dockerfile: ./php/Dockerfile
        container_name: php
        volumes:
            -   ./src:/var/www/project
        ports:
            - "9000:9000"
        networks:
            - nmpn

    #node
    node:
        image: node:lts
        container_name: node
        volumes:
            - ./src:/var/www/project
        working_dir: /var/www/project
        networks:
            - nmpn

    #phpmyadmin
    phpmyadmin:
        image: phpmyadmin:latest
        container_name: phpmyadmin
        restart: always
        environment:
            - PMA_ARBITRARY=1
        ports:
            - '9001:80'
        networks:
            - nmpn